### ISSUE TITLE
fatal error: 'experimental/filesystem' file not found

### ISSUE THREAD

**Issue by michaelkamprath** [tornupnegatives/TMS-Express#16]
When I am installing using Homebrew on MacOS 13.4, the build fails with the following error:

```
==> Installing tornupnegatives/tmsexpress/tms-express
==> cmake -S . -B build
==> make -C build
Last 15 lines from /Users/michael/Library/Logs/Homebrew/tms-express/02.make:
make[2]: *** [CMakeFiles/TMS-Express.dir/src/Interfaces/BitstreamGenerator.cpp.o] Error 1
/tmp/tms-express-20230611-22591-1tgnyn4/TMS-Express-1.1.2/src/main.cpp:6:10: fatal error: 'experimental/filesystem' file not found
#include <experimental/filesystem>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/TMS-Express.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/TMS-Express.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 48%] Linking CXX static library ../../../lib/libgtest.a
cd /tmp/tms-express-20230611-22591-1tgnyn4/TMS-Express-1.1.2/build/_deps/googletest-build/googletest && /usr/local/Cellar/cmake/3.26.4/bin/cmake -P CMakeFiles/gtest.dir/cmake_clean_target.cmake
cd /tmp/tms-express-20230611-22591-1tgnyn4/TMS-Express-1.1.2/build/_deps/googletest-build/googletest && /usr/local/Cellar/cmake/3.26.4/bin/cmake -E cmake_link_script CMakeFiles/gtest.dir/link.txt --verbose=1
/usr/bin/ar qc ../../../lib/libgtest.a "CMakeFiles/gtest.dir/src/gtest-all.cc.o"
/usr/bin/ranlib ../../../lib/libgtest.a
[ 48%] Built target gtest
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/tornupnegatives/homebrew-tmsexpress/issues
```

**Comment by tornupnegatives** [comment]
Thanks for raising this issue. Apple has updated their Clang compiler to support a newer version of the C++ standard, which bumped `<filesystem>` out of the `experimental` namespace. 

I have addressed this issue in my development branch, which will be merged into main once I finish the GUI. If you would like to compile the project yourself in the meantime, please refer to commit 955dbb7.

**Comment by michaelkamprath** [comment]
> I have addressed this issue in my development branch, which will be merged into main once I finish the GUI. If you would like to compile the project yourself in the meantime, please refer to commit [955dbb7](https://github.com/tornupnegatives/TMS-Express/commit/955dbb72583fef25f7d87f89566738a69e513675).

So it looks like you missed a location [here](url) as src/main.cpp wasn't altered in commit. I created #18 to fix that, and this allows me to build the tool on my MacOS 13.4 computer.

**Comment by tornupnegatives** [comment]
> > I have addressed this issue in my development branch, which will be merged into main once I finish the GUI. If you would like to compile the project yourself in the meantime, please refer to commit [955dbb7](https://github.com/tornupnegatives/TMS-Express/commit/955dbb72583fef25f7d87f89566738a69e513675).
> 
> 
> 
> So it looks like you missed a location [here](url) as src/main.cpp wasn't altered in commit. I created #18 to fix that, and this allows me to build the tool on my MacOS 13.4 computer.

Thank you, kind sir. I will merge this into main and update the Homebrew releases after work today. In the upcoming V2 release, I will also provide pre-compiled binaries so that things like this aren't so much of an issue.
